#for openshift to work we need to relax hosts.allow file/rules

#common ansible configuration
ansible_ssh_private_key_file: /home/mjudeiki/.ssh/xxxxx.pem

ansible_ssh_user: ec2-user

ansible_become: yes
invetory_provider: terraform

#static config
containerized: true
# these are needed due: https://bugzilla.redhat.com/show_bug.cgi?id=1460999
is_atomic: false
is_containerized: true

# OCP PRE config
rh_pool: xxxxxx
rh_username: xxxxx
rh_password: xxxxxx

rh_repos:
 - rhel-7-server-rpms
 - rhel-7-server-extras-rpms
 - rhel-7-server-ose-3.7-rpms
 - rhel-7-fast-datapath-rpms
 - rh-gluster-3-for-rhel-7-server-rpms

ocp_pre_packages:
 - wget 
 - git 
 - net-tools 
 - bind-utils 
 - iptables-services 
 - bridge-utils 
 - bash-completion 
 - kexec-tools 
 - sos 
 - psacct
 - python-passlib

docker_storage_disk: /dev/xvdc































