
os_firewall_use_firewalld: True

######## Openshift Default Config
#config, needed to be updated each install
openshift_master_cluster_hostname: ec2-18-232-107-246.compute-1.amazonaws.com
openshift_master_cluster_public_hostname: ec2-18-232-107-246.compute-1.amazonaws.com
openshift_master_default_subdomain: apps.54.144.111.190.xip.io

openshift_disable_check: memory_availability
ansible_service_broker_install: true

openshift_enable_service_catalog: true

#deploy gluster block
openshift_storage_glusterfs_registry_block_deploy: true
openshift_storage_glusterfs_block_deploy: true
openshift_storage_glusterfs_block_host_vol_size: 15
openshift_storage_glusterfs_block_storageclass: True
openshift_storage_glusterfs_storageclass_default: True
openshift_storage_glusterfs_block_storageclass_default: False
openshift_storage_glusterfs_s3_deploy: True
openshift_storage_glusterfs_s3_account: admin
openshift_storage_glusterfs_s3_user: user
openshift_storage_glusterfs_s3_password: admin@123

#static config
containerized: true
# these are needed due: https://bugzilla.redhat.com/show_bug.cgi?id=1460999
is_atomic: false
is_containerized: true
#openshift_crio_use: true
#openshift_use_crio_only: true

deployment_type: openshift-enterprise
#openshift_release: "v3.9"
#docker_version: 1.12.6
#openshift_image_tag: v3.7.23
#openshift_version: 3.7.23
openshift_docker_additional_registries: registry.access.redhat.com
openshift_docker_disable_push_dockerhub: True
openshift_docker_options: "--selinux-enabled --log-driver=json-file --log-opt max-size=50m --ipv6=false"
osm_controller_lease_ttl: 30
openshift_master_htpasswd_users: {'admin': '$apr1$m3IT5Wa4$EMAP84Ntp/QSR2SZVFRMu.', 'user': '$apr1$jcQ/OofR$.2oK.KhiUycvk4gLcQxHR.'}
openshift_master_identity_providers: [{'name': 'htpasswd', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

#openshift_node_kubelet_args: {'pods-per-core': ['70'], 'max-pods': ['254'], 'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80'],'kube-reserved': ['memory=500Mi'], 'system-reserved': ['memory=500Mi'] }

#prometheus
openshift_hosted_prometheus_deploy: true
openshift_prometheus_storage_type: pvc
#openshift_prometheus_pvc_name: prometheus
#openshift_prometheus_pvc_size: 50Gi
#openshift_prometheus_pvc_access_modes: [ReadWriteOnce] 
#openshift_prometheus_pvc_pv_selector: ""
openshift_prometheus_sc_name: "glusterfs-storage-block"

openshift_prometheus_alertmanager_storage_type: pvc
#openshift_prometheus_alertmanager_pvc_name: prometheus-alertmanager
#openshift_prometheus_alertmanager_pvc_size: 10Gi
#openshift_prometheus_alertmanager_pvc_access_modes: [ReadWriteOnce]
#openshift_prometheus_alertmanager_pvc_pv_selector: ""
openshift_prometheus_alertmanager_sc_name: "glusterfs-storage-block"

openshift_prometheus_alertbuffer_storage_type: pvc
#openshift_prometheus_alertbuffer_pvc_name: prometheus-alertbuffer
#openshift_prometheus_alertbuffer_pvc_size: 10Gi"
#openshift_prometheus_alertbuffer_pvc_access_modes: [ReadWriteOnce]
#openshift_prometheus_alertbuffer_pvc_pv_selector: ""
openshift_prometheus_alertbuffer_sc_name: "glusterfs-storage-block"


openshift_prometheus_storage_class: glusterfs-storage-block
openshift_prometheus_alertmanager_pvc_name: alertmanager
openshift_prometheus_alertbuffer_pvc_name: alertbuffer
openshift_prometheus_alertbuffer_pvc_size: 10G
openshift_prometheus_pvc_access_modes: [ReadWriteOnce]
openshift_prometheus_node_selector: { "node-role.kubernetes.io/infra": "true" }

#metrics
#openshift_metrics_install_metrics: True
#openshift_hosted_metrics_storage_kind: dynamic
#openshift_metrics_cassandra_storage_type: dynamic

osm_use_cockpit: true
osm_cockpit_plugins: "['cockpit-kubernetes']"
openshift_master_cluster_method: native
openshift_master_access_token_max_seconds: 86400
openshift_master_auth_token_max_seconds: 500
openshift_master_max_requests_inflight: 500
openshift_hosted_router_selector: 'node-role.kubernetes.io/infra=true'
openshift_hosted_registry_selector: 'node-role.kubernetes.io/infra=true'
template_service_broker_selector: { "node-role.kubernetes.io/infra": "true" }
osm_default_node_selector: 'node-role.kubernetes.io/compute=true'
openshift_schedulable_master: "false"
openshift_schedulable_etcd: "false"
openshift_hosted_router_replicas: 1
openshift_hosted_registry_replicas: 1
os_sdn_network_plugin_name: "'redhat/openshift-ovs-multitenant'"
osm_cluster_network_cidr: 10.1.0.0/16
openshift_portal_net: 172.30.0.0/16
#openshift_master_api_port: 443
#openshift_master_console_port: 443
openshift_master_session_name: ssn
openshift_master_session_max_seconds: 3600
openshift_set_hostname: false
logrotate_scripts: "[{\"name\": \"syslog\", \"path\": \"/var/log/cron\\n/var/log/maillog\\n/var/log/messages\\n/var/log/secure\\n/var/log/spooler\\n\", \"options\": [\"daily\", \"rotate 7\", \"compress\", \"sharedscripts\", \"missingok\"], \"scripts\": {\"postrotate\": \"/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true\"}}]"
openshift_clock_enabled: true
openshift_install_examples: true
openshift_master_api_env_vars: "{\"ENABLE_HTTP2\": \"true\"}"
openshift_master_controllers_env_vars: "{\"ENABLE_HTTP2\": \"true\"}"
openshift_node_env_vars: "{\"ENABLE_HTTP2\": \"true\"}"
#openshift_master_audit_config: "{\"enabled\": true, \"auditFilePath\": \"/var/log/audit-ocp.log\", \"maximumFileRetentionDays\": 10, \"maximumFileSizeMegabytes\": 10, \"maximumRetainedFiles\": 10}"
openshift_master_audit_config: {"basicAuditEnabled": true}

openshift_hosted_registry_storage_kind: glusterfs
#openshift_metrics_hawkular_cert: "{{inventory_dir}}/../files/certs/xxxxxx.crt"
#openshift_metrics_hawkular_key: "{{inventory_dir}}/../files/certs/xxxxxx.key"
#openshift_metrics_cassandra_replicas: 3
#openshift_http_proxy: http://proxy.xxxxxxx:8080
#openshift_https_proxy: https://proxy.xxxxxxx:8080
#openshift_builddefaults_http_proxy: http://proxy.xxxxxxx:8080
#openshift_builddefaults_https_proxy: https://proxy.xxxxxxx:8080
#openshift_builddefaults_git_http_proxy: http://proxy.xxxxxxx:8080
#openshift_builddefaults_git_https_proxy: https://proxy.xxxxxxx:8080


# Logging
openshift_logging_install_logging: true
openshift_logging_es_memory_limit: 1G
openshift_logging_fluentd_memory_limit: 1G
#openshift_logging_kibana_hostname=kibana.example.com
#openshift_logging_master_public_url=https://master
openshift_logging_curator_nodeselector: "{'node-role.kubernetes.io/infra':'true'}"
openshift_logging_kibana_nodeselector: "{'node-role.kubernetes.io/infra':'true'}"
openshift_logging_es_nodeselector: "{'node-role.kubernetes.io/infra':'true'}"
openshift_logging_elasticsearch_storage_type: pvc
openshift_logging_elasticsearch_pvc_storage_class_name: glusterfs-storage-block

#grafana
openshift_grafana_node_selector: "{'node-role.kubernetes.io/infra':'true'}"
openshift_grafana_node_exporter: true

openshift_enable_unsupported_configurations: true