---


# ansible host file overides
- name: overide groups for terraform
  add_host: name={{ item[0] }} groups={{ item[1]}} 
  with_nested: 
   - "{{ groups['role_masters'] }}"
   - [ 'masters', 'etcd', 'nodes', 'infra' ]
  when: invetory_provider == "terraform"

# ansible host file overides
- name: overide groups for terraform
  add_host: name={{ item[0] }} groups={{ item[1]}} 
  with_nested: 
   - "{{ groups['role_nodes'] }}"
   - [ 'nodes' ]
  when: invetory_provider == "terraform"

# ansible host file overides
- name: overide groups for terraform
  add_host: name={{ item[0] }} groups={{ item[1]}} 
  with_nested: 
   - "{{ groups['role_glusterfs'] }}"
   - [ 'glusterfs', 'nodes' ]
  when: invetory_provider == "terraform"

- name: print all ansible groups
  debug:
    msg: "{{ groups }}"

# tasks file for ocp-pre-hooks

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ocp_pre_packages }}"
  when: not containerized == true