---

- name: Configure invetory groups
  hosts: all
  
  roles:
  - { role: ocp-terraform-pre, when: invetory_provider == "terraform" }

- hosts: bastion
  roles:
   - ssh
  tasks:
    - name: Install dependencies for ocp-ansible-wrapper project onto bastion
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - unzip
        - ansible

    - name: Clean artifact path
      file:
        state: absent
        path: "openshift-ansible-wrapper"

    - name: clone ocp-ansible-wrapper project
      command: git clone https://github.com/mjudeikis/openshift-ansible-wrapper.git 
      with_items:
       - "git clone https://github.com/mjudeikis/openshift-ansible-wrapper.git"
       - "cd openshift-ansible-wrapper && make setup"