---
- name: Configure invetory groups
  hosts: all
  vars:
    openshift_metrics_install_metrics: true
  
  roles:
  - { role: ocp-terraform-pre, when: invetory_provider == "terraform" }

- include: ../openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml