---

- name: Configure invetory groups
  hosts: all
  
  roles:
  - { role: ocp-terraform-pre, when: invetory_provider == "terraform" }

- include: ../openshift-ansible/playbooks/openshift-hosted/config.yml
- include: ../openshift-ansible/playbooks/openshift-web-console/config.yml
 